export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNUP_START = "SIGNUP_START";

export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const FETCH_ALL_PETS_SUCCESS = "FETCH_ALL_PETS_SUCCESS";
export const FETCH_PETS_START = "FETCH_PETS_START";
export const FETCH_PETS_BY_CATEGORY_SUCCESS = "FETCH_PETS_BY_CATEGORY_SUCCESS";
export const FETCH_PETS_FAILURE = "FETCH_PETS_FAILURE";

export const LOGOUT = "LOGOUT";
